/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(diff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d14ef669ad54ccc6c4993354e186e095)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/experimental/diff.h>
// pydoc.h is automatically generated in the build directory
#include <diff_pydoc.h>

void bind_diff(py::module& m)
{

    using diff    = gr::experimental::diff;


    py::class_<diff, gr::block, gr::basic_block,
        std::shared_ptr<diff>>(m, "diff", D(diff))

        .def(py::init(&diff::make),
           D(diff,make)
        )
        



        ;




}








